{% set name = "muparserx" %}
{% set version = "4.0.8" %}

package:
  name: muparserx
  version: {{ version }}

source:
  url: https://github.com/beltoforion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5913e0a4ca29a097baad1b78a4674963bc7a06e39ff63df3c73fbad6fadb34e1

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('muparserx', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
  host:
    - llvm-openmp  # [osx]
test:
  commands:
    - test -f ${PREFIX}/include/muparserx/mpParser.h  # [unix]
    - test -f ${PREFIX}/lib/libmuparserx${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/muparserx.pc  # [unix]
    - test -f ${PREFIX}/share/cmake/muparserx/muparserxConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/muparserx/muparserxConfig.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muparserx\\mpParser.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\muparserx.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\cmake\\muparserxConfigVersion.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\cmake\\muparserxConfig.cmake exit 1  # [win]



about:
  home: https://beltoforion.de/en/muparserx
  license: BSD-2-Clause
  license_file: License.txt
  summary: A C++ Library for Parsing Expressions with Strings, Complex Numbers, Vectors, Matrices and more.

extra:
  recipe-maintainers:
    - wshanks
