{% set name = "muparserx" %}
{% set version = "4.0.12" %}

package:
  name: muparserx
  version: {{ version }}

source:
  url: https://github.com/beltoforion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 941c79f9b8b924f2f22406af8587177b4b185da3c968dbe8dc371b9dbe117f6e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('muparserx', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
  host:
    - llvm-openmp  # [osx]
test:
  commands:
    - test -f ${PREFIX}/include/muparserx/mpParser.h
    - test -f ${PREFIX}/lib/libmuparserx${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/muparserx.pc
    - test -f ${PREFIX}/share/cmake/muparserx/muparserxConfigVersion.cmake
    - test -f ${PREFIX}/share/cmake/muparserx/muparserxConfig.cmake

about:
  home: https://beltoforion.de/en/muparserx
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A C++ Library for Parsing Expressions with Strings, Complex Numbers, Vectors, Matrices and more.

extra:
  recipe-maintainers:
    - wshanks
